apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-ingressroute
  namespace: minio-tenant
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`minio.kgb.birtdata.com`)
      kind: Rule
      services:
        - name: minio
          port: 9000
