apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kgb-birtdata-com-homer-tls
  namespace: homer
spec:
  secretName: homer-tls
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - birtdata.com
