apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: Kustomize
resources:
  - ./metallb/pool.yaml
  - ./longhorn/traefik-config.yaml
  - ./pihole/traefik-config.yaml
  - ./homer/traefik-config.yaml
