apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-ingressroute
  namespace: paperless
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`paperless.kgb.birtdata.com`)
      kind: Rule
      services:
        - name: paperless-paperless-ngx
          port: 8000
