authentik:
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.io, and is fully opt-in
  error_reporting:
      enabled: true
server:
  ingress:
    # Specify kubernetes ingress controller class name
      ingressClassName: traefik
      enabled: true
      hosts:
          - authentik.kgb.birtdata.com
      pathType: Prefix
      paths:
          - "/"

postgresql:
  enabled: true
  auth:
    existingSecret: authentik-postgresql
redis:
  enabled: true
