configmap:
  config:
    enabled: true
    data:
      # Services
      # First level array represents a group.
      # Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
      services:
        - name: "System"
          icon: "fas fa-code-branch"
          # A path to an image can also be provided. Note that icon take precedence if both icon and logo are set.
          # logo: "path/to/logo"
          # class: "highlight-purple" # Optional css class to add on the service group. 
          items:
            - name: "Awesome app"
              subtitle: "Bookmark example"
              tag: "app"
              url: "1"
              target: "_blank" # optional html tag target attribute
            - name: "Another one"
              logo: "assets/tools/sample2.png"
              subtitle: "Another application"
              tag: "app"
              # Optional tagstyle
              tagstyle: "is-success"
              url: "#"
        - name: "Other group"
          icon: "fas fa-heartbeat"
          items:
            - name: "Pi-hole"
              logo: "assets/tools/sample.png"
              # subtitle: "Network-wide Ad Blocking" # optional, if no subtitle is defined, PiHole statistics will be shown
              tag: "other"
              url: "http://192.168.50.65/admin"
              type: "PiHole" # optional, loads a specific component that provides extra features. MUST MATCH a file name (without file extension) available in `src/components/services`
              target: "_blank" # optional html a tag target attribute
              # class: "green" # optional custom CSS class for card, useful with custom stylesheet
              # background: red # optional color for card to set color directly without custom stylesheet
