---
DNS1:
  192.168.50.1
persistentVolumeClaim:
  enabled: true
serviceWeb:
  http:
    port: 80
  https:
    port: 443
serviceDns:
  loadBalancerIP: 192.168.50.100
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1
