apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-ingressroute
  namespace: immich
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`immich.kgb.birtdata.com`)
      kind: Rule
      services:
        - name: immich-server
          port: 3001
