repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/
  - name: traefik
    url: https://traefik.github.io/charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: tailscale
    url: https://pkgs.tailscale.com/helmcharts
  - name: immich
    url: https://immich-app.github.io/immich-charts
  - name: djjudas21
    url: https://djjudas21.github.io/charts/
  - name: minio
    url: https://operator.min.io
  - name: authentik
    url: https://charts.goauthentik.io
  - name: jetstack
    url: https://charts.jetstack.io
---
releases:
  # Distributed storage
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.6.2

  # Load balancer
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.14.5

  # pihole
  - name: pihole
    namespace: pihole-system
    chart: mojo2600/pihole
    version: 2.18.0
    values:
      - ./values/pihole.values.yaml

  # Ingress for local network
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: 29.0.1
    values:
      - ./values/traefik.values.yaml
  
  # Tailscale - remote access
  - name: tailscale
    namespace: tailscale-system
    chart: tailscale/tailscale-operator
    version: 1.68.1
    values:
      - ./secrets/tailscale.yaml

  # Homer - homepage for all services
  - name: homer
    namespace: homer
    chart: djjudas21/homer
    version: 8.1.12
    values:
      - ./values/homer.values.yaml

  # Immich - Photo/Video
  - name: immich
    namespace: immich
    chart: immich/immich
    version: 0.7.0
    values:
      - ./values/immich.values.yaml
  
  # Paperless - Document DB
  - name: paperless
    namespace: paperless
    chart: oci://ghcr.io/gabe565/charts/paperless-ngx
    version: 0.18.1
    values:
      - ./values/paperless.values.yaml
  
  # Minio - S3 compatible storage
  - name: minio
    namespace: minio-operator
    chart: minio/operator
    version: 6.0.0
    values:
      - ./values/minio-operator.values.yaml
  
  - name: minio-tenant
    namespace: minio-tenant
    chart: minio/tenant
    version: 6.0.0
    values:
      - ./values/minio-tenant.values.yaml
  
  # Authentik - SSO
  - name: authentik
    namespace: authentik
    chart: authentik/authentik
    version: 2024.6.1
    values:
      - ./values/authentik.yaml
      - ./secrets/authentik.yaml
  
  # Cert-manager - SSL
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.15.1
    values:
      - ./values/cert-manager.values.yaml
